# Generated by Django 3.2.5 on 2021-08-04 10:02

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0003_auto_20210804_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='about_us_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myhouse_admin.aboutuspage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AboutUsPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.get_upload_path)),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhouse_admin.aboutuspage')),
            ],
        ),
    ]
