# Generated by Django 3.2.5 on 2021-08-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0005_aboutuspageadditionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspageadditionalimage',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='myhouse_admin.aboutuspage'),
        ),
        migrations.AlterField(
            model_name='aboutuspageimage',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myhouse_admin.aboutuspage'),
        ),
    ]
