# Generated by Django 3.2.5 on 2021-09-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_owner_id'),
        ('myhouse_admin', '0007_auto_20210829_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='users.owner'),
        ),
    ]
