# Generated by Django 3.2.5 on 2021-09-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0008_auto_20210906_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_account', to='myhouse_admin.flat'),
        ),
    ]
