# Generated by Django 3.2.5 on 2021-09-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0009_alter_personalaccount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myhouse_admin.unit'),
        ),
    ]
