# Generated by Django 3.2.5 on 2021-09-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0010_alter_service_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_services', to='myhouse_admin.tariff'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name',)},
        ),
    ]
