# Generated by Django 3.2.5 on 2021-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0011_auto_20210910_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='summary',
            field=models.FloatField(default=0.0),
        ),
    ]
