# Generated by Django 3.2.5 on 2021-09-13 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0012_personalaccount_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxrecord',
            name='summary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
