# Generated by Django 3.2.5 on 2021-09-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0014_auto_20210913_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxrecord',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhouse_admin.personalaccount'),
        ),
    ]
