# Generated by Django 3.2.5 on 2021-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0015_alter_cashboxrecord_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='number',
            field=models.CharField(default='123123123', max_length=50, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
