# Generated by Django 3.2.5 on 2021-09-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0019_auto_20210918_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptservice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_services', to='myhouse_admin.receipt'),
        ),
    ]
