# Generated by Django 3.2.5 on 2021-09-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0020_alter_receiptservice_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='summary',
        ),
    ]
