# Generated by Django 3.2.5 on 2021-09-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse_admin', '0021_remove_personalaccount_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxrecord',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhouse_admin.receipt'),
        ),
    ]
