# Generated by Django 3.2.5 on 2021-08-03 09:45

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='owner',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='viber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
