# Generated by Django 3.2.5 on 2021-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210803_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ID',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID пользователя'),
        ),
    ]
